name: Update tested AGP versions
on:
  workflow_dispatch:

jobs:
  update_agp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew updateAgpVersions
      - uses: peter-evans/create-pull-request@v5
        with:
          branch: automated/update-agp-versions
          commit-message: Update tested AGP versions
          title: Update tested AGP versions
          body: |
            Update tested AGP versions
          labels: a:chore
          assignees: eskatos
          reviewers: eskatos
          draft: true
