name: Update tested AGP versions
on:
  workflow_dispatch:

jobs:
  update_agp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: pr_check
        run: |
          _check_branch=$(git ls-remote --heads origin automated/update-agp-versions)
          if [[ -z ${_check_branch} ]]; then
            echo "remote branch `automated/update-agp-versions` does not exist, let's continue"
            echo "continue=true" >> "$GITHUB_OUTPUT"
          else
            echo "remote branch `automated/update-agp-versions` already exists, let's stop here"
          fi
      - uses: actions/setup-java@v3
        if: steps.pr_check.outputs.continue
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        if: steps.pr_check.outputs.continue
      - run: ./gradlew updateAgpVersions
        if: steps.pr_check.outputs.continue
      - uses: peter-evans/create-pull-request@v5
        if: steps.pr_check.outputs.continue
        with:
          branch: automated/update-agp-versions
          commit-message: Update tested AGP versions
          title: Update tested AGP versions
          body: |
            Update tested AGP versions
          labels: a:chore
          assignees: eskatos
          reviewers: eskatos
          draft: true
